### ISSUE TITLE
Charset content type identifier not supported

### ISSUE THREAD

**Issue by zlaroche** [EXXETA/openapi-cop#112]
I've noticed that the source code doe does not properly register the response validator if an operation's content type is defined with the charset identifier, such as

```
content:
          application/json; charset=UTF-8:
```
The issue seems to be line `438` of `node_modules/openapi-backend/validation.js`, where it simply checks to see if the content is `application/json`, this missing an `application/json` with a charset identifier.

```
 const validator = this.getAjv(ValidationContext.Response);
        _.mapKeys(operation.responses, (res, status) => {
            const response = res;
            if (response.content && response.content['application/json'] && **response.content['application/json'].schema) {
                const validateFn = response.content['application/json'].schema;
                responseValidators[status] = validator.compile(validateFn);**
            }
            return null;
        });
        this.statusBasedResponseValidators[operationId] = responseValidators;
```

**Comment by LexLuengas** [comment]
As far as I can tell, neither the JSON spec nor the Media Type spec allow the usage of the "charset" parameter together with "application/json", so that would mean your example is part of an invalid OpenAPI document. For a better argumentation see https://github.com/axios/axios/issues/2154#issuecomment-591453106 and https://github.com/request/request/issues/383.
